In [1]:
import pandas as pd
import numpy as np
from pathlib import Path 
import os 
import matplotlib.pyplot as plt

In [2]:
path = os.path.abspath(os.path.join(os.getcwd(), '..'))
path = os.path.join(path, "data", "raw", "dorm_prices.csv")

dorms = pd.read_csv(path)

In [3]:
dorms["beds"] = dorms["room_type"].str.split("-").str[0].astype(int)

In [4]:
dorms["facilities"] = dorms["room_type"].str.contains("se soc. zař.", case=False, na=False).map({True: "Yes", False: "No"})

In [5]:
dorms["monthly_cost"]=dorms["price"]*30

In [6]:
dorm_stats = dorms.groupby(
    ["beds", "facilities"]
).agg(
    avg_cost=("monthly_cost", "mean"),
    count=("monthly_cost", "size")
).reset_index()

In [7]:
dorm_stats

   beds facilities  avg_cost  count
0     1         No    6120.0      6
1     1        Yes    8035.0      6
2     2         No    4815.0      6
3     2        Yes    5910.0      7
4     3         No    4087.5      4
5     3        Yes    3975.0      2
6     4         No    3765.0      2

In [8]:
dorms

,dorm,room_type,price,beds,facilities,monthly_cost
0,Kolej Budeč,1-lůžkový pokoj bez soc. zař.,230,1,No,6900
1,Kolej Budeč,2-lůžkový pokoj bez soc. zař.,176,2,No,5280
2,Kolej Budeč,3-lůžkový pokoj bez soc. zař.,146,3,No,4380
3,Kolej Hostivař,1-lůžkový pokoj se soc. zař.,196,1,Yes,5880
4,Kolej Hostivař,2-lůžkový pokoj bez soc. zař.,151,2,No,4530
5,Kolej Hostivař,2-lůžkový pokoj se soc. zař.,164,2,Yes,4920
6,Kolej Hvězda,1-lůžkový pokoj bez soc. zař.,198,1,No,5940
7,Kolej Hvězda,2-lůžkový pokoj bez soc. zař.,155,2,No,4650
8,Kolej Hvězda,2-lůžkový pokoj se soc. zař.,242,2,Yes,7260
9,Kolej Hvězda,1-lůžkový pokoj se soc. zař.,269,1,Yes,8070
10,Kolej Jednota,1-lůžkový pokoj bez soc. zař.,232,1,No,6960
11,Kolej Jednota,2-lůžkový pokoj bez soc. zař.,193,2,No,5790
12,Kolej Jednota,3-lůžkový pokoj bez soc. zař.,154,3,No,4620
13,Kolej Jednota,4-lůžkový pokoj bez soc. zař.,144,4,No,4320
14,Kolej Kajetánka,1-lůžkový pokoj se soc. zař.,233,1,Yes,6990
15,Kolej Kajetánka,2-lůžkový pokoj se soc. zař.,183,2,Yes,5490
16,Kolej Komenského,1-lůžkový pokoj se soc. zař.,267,1,Yes,8010
17,Kolej Na Větrníku,1-lůžkový pokoj bez soc. zař.,190,1,No,5700
18,Kolej Na Větrníku,2-lůžkový pokoj bez soc. zař.,140,2,No,4200
19,Kolej Na Větrníku,3-lůžkový pokoj bez soc. zař.,126,3,No,3780
20,Kolej Otava,1-lůžkový pokoj se soc. zař.,198,1,Yes,5940
21,Kolej Otava,2-lůžkový pokoj se soc. zař.,153,2,Yes,4590
22,Kolej Otava,3-lůžkový pokoj se soc. zař.,146,3,Yes,4380
23,Kolej Švehlova,1-lůžkový pokoj bez soc. zař.,176,1,No,5280
24,Kolej Švehlova,2-lůžkový pokoj bez soc. zař.,148,2,No,4440
25,Kolej Švehlova,3-lůžkový pokoj bez soc. zař.,119,3,No,3570
26,Kolej Švehlova,3-lůžkový pokoj se soc. zař.,119,3,Yes,3570
27,Kolej Švehlova,4-lůžkový pokoj bez soc. zař.,107,4,No,3210
28,Kolej 17. listopadu,2-lůžkový pokoj se soc. zař.,174,2,Yes,5220
29,Kolej Vltava,1-lůžkový pokoj se soc.zař.,198,1,No,5940
30,Kolej Vltava,2-lůžkový pokoj se soc. zař.,153,2,Yes,4590
31,Kolej Krystal,1-lůžkový pokoj se soc. zař.,444,1,Yes,13320
32,Kolej Krystal,2-lůžkový pokoj se soc. zař.,310,2,Yes,9300

In [12]:
output_path_stats = os.path.join('..', 'data', 'clean', 'dorm_stats.csv')
dorm_stats.to_csv(output_path_stats, index=False)

In [11]:
output_path_dorm = os.path.join('..', 'data', 'clean', 'dorm_clean.csv')
dorms.to_csv(output_path_dorm, index=False)