In [1]:
import pandas as pd
import numpy as np
from pathlib import Path 
import os 
import matplotlib.pyplot as plt
import random

In [2]:
pathm = os.path.abspath(os.path.join(os.getcwd(), '..'))
pathm = os.path.join(pathm, "data", "raw", "menza_prices.csv")

canteen = pd.read_csv(pathm)

In [3]:
canteen

,date,meal_type,name,price
0,2026-04-19,Polévka,Kuřecí vývar s nudlemi,22.0
1,2026-04-19,Hlavní jídlo,"Kuřecí roláda plněná, dušená rýže",103.0
2,2026-04-19,Hlavní jídlo,"Segedínský guláš, houskový knedlík",95.0
3,2026-04-19,Hlavní jídlo,"Mac and Cheese, malý míchaný salát",99.0
4,2026-04-19,Hlavní jídlo,"Čočkový kotlík, chléb",74.0
5,2026-04-19,Hlavní jídlo,"Vepřová kotleta na grilu, dip, americké brambory",107.0
6,2026-04-20,Polévka,Dršťková polévka z hlívy ústřičné,22.0
7,2026-04-20,Hlavní jídlo,"Hovězí stoganoff, dušená rýže",115.0
8,2026-04-20,Hlavní jídlo,"Domácí pečená sekaná, bramborová kaše, okurka",102.0
9,2026-04-20,Hlavní jídlo,Kuskusový nákyp se zeleninou,87.0
10,2026-04-20,Hlavní jídlo,Stir Fry rýžové nudle se zeleninou a edamame,115.0
11,2026-04-20,Hlavní jídlo,"Kuřecí stripsy,citrón, hranolky",124.0
12,2026-04-21,Polévka,Zeleninová polévka s praženou krupicí,22.0
13,2026-04-21,Hlavní jídlo,"Aljašská treska na rajčatech, bylinkách s petr...",105.0
14,2026-04-21,Hlavní jídlo,"Srbské vepřové rizoto sypané sýrem, červená ře...",87.0
15,2026-04-21,Hlavní jídlo,Tagliatelle s omáčkou Funghi,101.0
16,2026-04-21,Hlavní jídlo,"Ratatouille s červenými fazolemi, pitta chléb",118.0
17,2026-04-21,Hlavní jídlo,"Krůtí nudličky na bylinkách, hranolky",114.0
18,2026-04-22,Polévka,Zelná polévka s bramborem,22.0
19,2026-04-22,Hlavní jídlo,"Vepřová plec na smetaně, houskový knedlík",86.0
20,2026-04-22,Hlavní jídlo,Penne Pollo Spinaci s kuřecím masem,103.0
21,2026-04-22,Hlavní jídlo,Zapečené bramborové noky s dýní a cizrnou,98.0
22,2026-04-22,Hlavní jídlo,"VEGAN Smažený sýr gouda, vařené brambory, vega...",107.0
23,2026-04-22,Hlavní jídlo,"Srnčí ragú na víně, karlovarské knedlíky",129.0
24,2026-04-23,Polévka,Hrstková polévka,22.0
25,2026-04-23,Hlavní jídlo,"Plněné papriky přírodní, vařené brambory",106.0
26,2026-04-23,Hlavní jídlo,"Kuřecí maso kung - pao, jasmínová rýže",86.0
27,2026-04-23,Hlavní jídlo,"Ovocné knedlíky s tvarohem, cukrem a jogurtový...",108.0
28,2026-04-23,Hlavní jídlo,"Falafel s s míchaným salátem, 1/2 smažené hran...",124.0
29,2026-04-23,Hlavní jídlo,"Wrap s BBQ omáčkou , pečeným kuřecím stehenním...",108.0

In [6]:
canteen["date"] = pd.to_datetime(canteen["date"])

In [7]:
main_meal_mean=canteen[canteen["meal_type"]=="Hlavní jídlo"]["price"].mean()
soup_mean=canteen[canteen["meal_type"]=="Polévka"]["price"].mean()

In [8]:
canteen_clean=canteen[["meal_type","price"]]

In [9]:
canteen_stats = canteen_clean.groupby("meal_type").agg(
    avg_price=("price", "mean"),
    count=("price", "count")
).reset_index()

In [11]:
print(main_meal_mean, soup_mean)

104.04 22.0

In [12]:
daily_cost=main_meal_mean+soup_mean
weekly_cost=daily_cost*5
monthly_cost=weekly_cost*4
monthly_cost

np.float64(2520.8)

In [13]:
canteen_costs=pd.DataFrame({"days_per_week":range(1,6),
                           "weeks_per_month":4})

canteen_costs["monthly_cost"]=(
    canteen_costs["days_per_week"]*canteen_costs["weeks_per_month"]*(main_meal_mean+soup_mean)
)

canteen_costs=canteen_costs.drop(columns="weeks_per_month")
canteen_costs

   days_per_week  monthly_cost
0              1        504.16
1              2       1008.32
2              3       1512.48
3              4       2016.64
4              5       2520.80

In [14]:
output_path = os.path.join('..', 'data', 'clean', 'canteen_costs.csv')
canteen_costs.to_csv(output_path, index=False)