In [3]:
import pandas as pd
import numpy as np
from pathlib import Path 
import os 
import matplotlib.pyplot as plt

In [24]:
path = os.path.abspath(os.path.join(os.getcwd(), '..'))
path = os.path.join(path, "data", "raw", "dorm_prices.csv")

dorms = pd.read_csv(path)

In [28]:
dorms["beds"] = dorms["room_type"].str.split("-").str[0].astype(int)

In [29]:
dorms["facilities"] = dorms["room_type"].str.contains("se soc. zař.", case=False, na=False).map({True: "Yes", False: "No"})

In [30]:
dorms = dorms.rename(columns={"price": "monthly_cost"})
dorms

,dorm,room_type,monthly_cost,facilities,beds
0,Kolej Budeč,1-lůžkový pokoj bez soc. zař.,230,No,1
1,Kolej Budeč,2-lůžkový pokoj bez soc. zař.,176,No,2
2,Kolej Budeč,3-lůžkový pokoj bez soc. zař.,146,No,3
3,Kolej Hostivař,1-lůžkový pokoj se soc. zař.,196,Yes,1
4,Kolej Hostivař,2-lůžkový pokoj bez soc. zař.,151,No,2
5,Kolej Hostivař,2-lůžkový pokoj se soc. zař.,164,Yes,2
6,Kolej Hvězda,1-lůžkový pokoj bez soc. zař.,198,No,1
7,Kolej Hvězda,2-lůžkový pokoj bez soc. zař.,155,No,2
8,Kolej Hvězda,2-lůžkový pokoj se soc. zař.,242,Yes,2
9,Kolej Hvězda,1-lůžkový pokoj se soc. zař.,269,Yes,1
10,Kolej Jednota,1-lůžkový pokoj bez soc. zař.,232,No,1
11,Kolej Jednota,2-lůžkový pokoj bez soc. zař.,193,No,2
12,Kolej Jednota,3-lůžkový pokoj bez soc. zař.,154,No,3
13,Kolej Jednota,4-lůžkový pokoj bez soc. zař.,144,No,4
14,Kolej Kajetánka,1-lůžkový pokoj se soc. zař.,233,Yes,1
15,Kolej Kajetánka,2-lůžkový pokoj se soc. zař.,183,Yes,2
16,Kolej Komenského,1-lůžkový pokoj se soc. zař.,267,Yes,1
17,Kolej Na Větrníku,1-lůžkový pokoj bez soc. zař.,190,No,1
18,Kolej Na Větrníku,2-lůžkový pokoj bez soc. zař.,140,No,2
19,Kolej Na Větrníku,3-lůžkový pokoj bez soc. zař.,126,No,3
20,Kolej Otava,1-lůžkový pokoj se soc. zař.,198,Yes,1
21,Kolej Otava,2-lůžkový pokoj se soc. zař.,153,Yes,2
22,Kolej Otava,3-lůžkový pokoj se soc. zař.,146,Yes,3
23,Kolej Švehlova,1-lůžkový pokoj bez soc. zař.,176,No,1
24,Kolej Švehlova,2-lůžkový pokoj bez soc. zař.,148,No,2
25,Kolej Švehlova,3-lůžkový pokoj bez soc. zař.,119,No,3
26,Kolej Švehlova,3-lůžkový pokoj se soc. zař.,119,Yes,3
27,Kolej Švehlova,4-lůžkový pokoj bez soc. zař.,107,No,4
28,Kolej 17. listopadu,2-lůžkový pokoj se soc. zař.,174,Yes,2
29,Kolej Vltava,1-lůžkový pokoj se soc.zař.,198,No,1
30,Kolej Vltava,2-lůžkový pokoj se soc. zař.,153,Yes,2
31,Kolej Krystal,1-lůžkový pokoj se soc. zař.,444,Yes,1
32,Kolej Krystal,2-lůžkový pokoj se soc. zař.,310,Yes,2

In [31]:
dorm_stats = dorms.groupby(
    ["beds", "facilities"]
).agg(
    avg_cost=("monthly_cost", "mean"),
    count=("monthly_cost", "size")
).reset_index()

In [32]:
dorm_stats

   beds facilities    avg_cost  count
0     1         No  204.000000      6
1     1        Yes  267.833333      6
2     2         No  160.500000      6
3     2        Yes  197.000000      7
4     3         No  136.250000      4
5     3        Yes  132.500000      2
6     4         No  125.500000      2