In [3]:
import pandas as pd
import numpy as np
from pathlib import Path 
import os 
import matplotlib.pyplot as plt

In [4]:
path = os.path.abspath(os.path.join(os.getcwd(), '..'))
path = os.path.join(path, "data", "raw", "dorm_prices.csv")

dorms = pd.read_csv(path)

In [5]:
dorms["beds"] = dorms["room_type"].str.split("-").str[0].astype(int)

In [6]:
dorms["facilities"] = dorms["room_type"].str.contains("se soc. zař.", case=False, na=False).map({True: "Yes", False: "No"})

In [9]:
dorms = dorms.rename(columns={"price": "monthly_cost"})
dorms

,dorm,room_type,monthly_cost,beds,facilities
0,Kolej Budeč,1-lůžkový pokoj bez soc. zař.,230,1,No
1,Kolej Budeč,2-lůžkový pokoj bez soc. zař.,176,2,No
2,Kolej Budeč,3-lůžkový pokoj bez soc. zař.,146,3,No
3,Kolej Hostivař,1-lůžkový pokoj se soc. zař.,196,1,Yes
4,Kolej Hostivař,2-lůžkový pokoj bez soc. zař.,151,2,No
5,Kolej Hostivař,2-lůžkový pokoj se soc. zař.,164,2,Yes
6,Kolej Hvězda,1-lůžkový pokoj bez soc. zař.,198,1,No
7,Kolej Hvězda,2-lůžkový pokoj bez soc. zař.,155,2,No
8,Kolej Hvězda,2-lůžkový pokoj se soc. zař.,242,2,Yes
9,Kolej Hvězda,1-lůžkový pokoj se soc. zař.,269,1,Yes
10,Kolej Jednota,1-lůžkový pokoj bez soc. zař.,232,1,No
11,Kolej Jednota,2-lůžkový pokoj bez soc. zař.,193,2,No
12,Kolej Jednota,3-lůžkový pokoj bez soc. zař.,154,3,No
13,Kolej Jednota,4-lůžkový pokoj bez soc. zař.,144,4,No
14,Kolej Kajetánka,1-lůžkový pokoj se soc. zař.,233,1,Yes
15,Kolej Kajetánka,2-lůžkový pokoj se soc. zař.,183,2,Yes
16,Kolej Komenského,1-lůžkový pokoj se soc. zař.,267,1,Yes
17,Kolej Na Větrníku,1-lůžkový pokoj bez soc. zař.,190,1,No
18,Kolej Na Větrníku,2-lůžkový pokoj bez soc. zař.,140,2,No
19,Kolej Na Větrníku,3-lůžkový pokoj bez soc. zař.,126,3,No
20,Kolej Otava,1-lůžkový pokoj se soc. zař.,198,1,Yes
21,Kolej Otava,2-lůžkový pokoj se soc. zař.,153,2,Yes
22,Kolej Otava,3-lůžkový pokoj se soc. zař.,146,3,Yes
23,Kolej Švehlova,1-lůžkový pokoj bez soc. zař.,176,1,No
24,Kolej Švehlova,2-lůžkový pokoj bez soc. zař.,148,2,No
25,Kolej Švehlova,3-lůžkový pokoj bez soc. zař.,119,3,No
26,Kolej Švehlova,3-lůžkový pokoj se soc. zař.,119,3,Yes
27,Kolej Švehlova,4-lůžkový pokoj bez soc. zař.,107,4,No
28,Kolej 17. listopadu,2-lůžkový pokoj se soc. zař.,174,2,Yes
29,Kolej Vltava,1-lůžkový pokoj se soc.zař.,198,1,No
30,Kolej Vltava,2-lůžkový pokoj se soc. zař.,153,2,Yes
31,Kolej Krystal,1-lůžkový pokoj se soc. zař.,444,1,Yes
32,Kolej Krystal,2-lůžkový pokoj se soc. zař.,310,2,Yes

In [10]:
dorm_stats = dorms.groupby(
    ["beds", "facilities"]
).agg(
    avg_cost=("monthly_cost", "mean"),
    count=("monthly_cost", "size")
).reset_index()

In [11]:
dorm_stats

   beds facilities    avg_cost  count
0     1         No  204.000000      6
1     1        Yes  267.833333      6
2     2         No  160.500000      6
3     2        Yes  197.000000      7
4     3         No  136.250000      4
5     3        Yes  132.500000      2
6     4         No  125.500000      2

In [12]:
os.chdir("..")
dorm_stats.to_csv("data/clean/dorm_stats.csv", index=False)

In [13]:
dorms.to_csv("data/clean/dorms_clean.csv", index=False)