In [3]:
import numpy as np
import pandas as pd 
import os
import requests
import json 
from bs4 import BeautifulSoup
import boto3
from IPython.display import HTML, display
import time 
import datetime

In [4]:
days=list(range(19,24))
data=[]
for day in days:
    url=f"https://kamweb.ruk.cuni.cz/webkredit/Api/Ordering/Menu?Dates=2026-04-{day}T22%3A00%3A00.000Z&CanteenId=7"
    response=requests.get(url).json()

    for group in response["groups"]:
        meal_kind=group["mealKindName"]
        date=group["date"]

        for row in group["rows"]:
            item=row["item"]
            data.append({
                'date': date,
                'meal_type': meal_kind,
                'name': item['mealName'],
                'price': item['price2']
            })
    time.sleep(1)

In [5]:
df=pd.DataFrame(data)
df

,date,meal_type,name,price
0,2026-04-19T22:00:00.0000000Z,Polévka,Kuřecí vývar s nudlemi,22.0
1,2026-04-19T22:00:00.0000000Z,Hlavní jídlo,"Kuřecí roláda plněná, dušená rýže",103.0
2,2026-04-19T22:00:00.0000000Z,Hlavní jídlo,"Segedínský guláš, houskový knedlík",95.0
3,2026-04-19T22:00:00.0000000Z,Hlavní jídlo,"Mac and Cheese, malý míchaný salát",99.0
4,2026-04-19T22:00:00.0000000Z,Hlavní jídlo,"Čočkový kotlík, chléb",74.0
5,2026-04-19T22:00:00.0000000Z,Hlavní jídlo,"Vepřová kotleta na grilu, dip, americké brambory",107.0
6,2026-04-19T22:00:00.0000000Z,Hlavní jídlo,Teplý bufet,269.5
7,2026-04-20T22:00:00.0000000Z,Polévka,Dršťková polévka z hlívy ústřičné,22.0
8,2026-04-20T22:00:00.0000000Z,Hlavní jídlo,"Hovězí stoganoff, dušená rýže",115.0
9,2026-04-20T22:00:00.0000000Z,Hlavní jídlo,"Domácí pečená sekaná, bramborová kaše, okurka",102.0
10,2026-04-20T22:00:00.0000000Z,Hlavní jídlo,Kuskusový nákyp se zeleninou,87.0
11,2026-04-20T22:00:00.0000000Z,Hlavní jídlo,Stir Fry rýžové nudle se zeleninou a edamame,115.0
12,2026-04-20T22:00:00.0000000Z,Hlavní jídlo,"Kuřecí stripsy,citrón, hranolky",124.0
13,2026-04-20T22:00:00.0000000Z,Hlavní jídlo,Teplý bufet,269.5
14,2026-04-21T22:00:00.0000000Z,Polévka,Zeleninová polévka s praženou krupicí,22.0
15,2026-04-21T22:00:00.0000000Z,Hlavní jídlo,"Aljašská treska na rajčatech, bylinkách s petr...",105.0
16,2026-04-21T22:00:00.0000000Z,Hlavní jídlo,"Srbské vepřové rizoto sypané sýrem, červená ře...",87.0
17,2026-04-21T22:00:00.0000000Z,Hlavní jídlo,Tagliatelle s omáčkou Funghi,101.0
18,2026-04-21T22:00:00.0000000Z,Hlavní jídlo,"Ratatouille s červenými fazolemi, pitta chléb",118.0
19,2026-04-21T22:00:00.0000000Z,Hlavní jídlo,"Krůtí nudličky na bylinkách, hranolky",114.0
20,2026-04-21T22:00:00.0000000Z,Hlavní jídlo,Teplý bufet,269.5
21,2026-04-22T22:00:00.0000000Z,Polévka,Zelná polévka s bramborem,22.0
22,2026-04-22T22:00:00.0000000Z,Hlavní jídlo,"Vepřová plec na smetaně, houskový knedlík",86.0
23,2026-04-22T22:00:00.0000000Z,Hlavní jídlo,Penne Pollo Spinaci s kuřecím masem,103.0
24,2026-04-22T22:00:00.0000000Z,Hlavní jídlo,Zapečené bramborové noky s dýní a cizrnou,98.0
25,2026-04-22T22:00:00.0000000Z,Hlavní jídlo,"VEGAN Smažený sýr gouda, vařené brambory, vega...",107.0
26,2026-04-22T22:00:00.0000000Z,Hlavní jídlo,"Srnčí ragú na víně, karlovarské knedlíky",129.0
27,2026-04-22T22:00:00.0000000Z,Hlavní jídlo,Teplý bufet,269.5
28,2026-04-23T22:00:00.0000000Z,Polévka,Hrstková polévka,22.0
29,2026-04-23T22:00:00.0000000Z,Hlavní jídlo,"Plněné papriky přírodní, vařené brambory",106.0
30,2026-04-23T22:00:00.0000000Z,Hlavní jídlo,"Kuřecí maso kung - pao, jasmínová rýže",86.0
31,2026-04-23T22:00:00.0000000Z,Hlavní jídlo,"Ovocné knedlíky s tvarohem, cukrem a jogurtový...",108.0
32,2026-04-23T22:00:00.0000000Z,Hlavní jídlo,"Falafel s s míchaným salátem, 1/2 smažené hran...",124.0
33,2026-04-23T22:00:00.0000000Z,Hlavní jídlo,"Wrap s BBQ omáčkou , pečeným kuřecím stehenním...",108.0
34,2026-04-23T22:00:00.0000000Z,Hlavní jídlo,Teplý bufet,269.5

In [6]:
df["date"]=df["date"].str.split("T").str[0]
df=df[df["name"]!="Teplý bufet"]
df=df.reset_index(drop=True)
df

,date,meal_type,name,price
0,2026-04-19,Polévka,Kuřecí vývar s nudlemi,22.0
1,2026-04-19,Hlavní jídlo,"Kuřecí roláda plněná, dušená rýže",103.0
2,2026-04-19,Hlavní jídlo,"Segedínský guláš, houskový knedlík",95.0
3,2026-04-19,Hlavní jídlo,"Mac and Cheese, malý míchaný salát",99.0
4,2026-04-19,Hlavní jídlo,"Čočkový kotlík, chléb",74.0
5,2026-04-19,Hlavní jídlo,"Vepřová kotleta na grilu, dip, americké brambory",107.0
6,2026-04-20,Polévka,Dršťková polévka z hlívy ústřičné,22.0
7,2026-04-20,Hlavní jídlo,"Hovězí stoganoff, dušená rýže",115.0
8,2026-04-20,Hlavní jídlo,"Domácí pečená sekaná, bramborová kaše, okurka",102.0
9,2026-04-20,Hlavní jídlo,Kuskusový nákyp se zeleninou,87.0
10,2026-04-20,Hlavní jídlo,Stir Fry rýžové nudle se zeleninou a edamame,115.0
11,2026-04-20,Hlavní jídlo,"Kuřecí stripsy,citrón, hranolky",124.0
12,2026-04-21,Polévka,Zeleninová polévka s praženou krupicí,22.0
13,2026-04-21,Hlavní jídlo,"Aljašská treska na rajčatech, bylinkách s petr...",105.0
14,2026-04-21,Hlavní jídlo,"Srbské vepřové rizoto sypané sýrem, červená ře...",87.0
15,2026-04-21,Hlavní jídlo,Tagliatelle s omáčkou Funghi,101.0
16,2026-04-21,Hlavní jídlo,"Ratatouille s červenými fazolemi, pitta chléb",118.0
17,2026-04-21,Hlavní jídlo,"Krůtí nudličky na bylinkách, hranolky",114.0
18,2026-04-22,Polévka,Zelná polévka s bramborem,22.0
19,2026-04-22,Hlavní jídlo,"Vepřová plec na smetaně, houskový knedlík",86.0
20,2026-04-22,Hlavní jídlo,Penne Pollo Spinaci s kuřecím masem,103.0
21,2026-04-22,Hlavní jídlo,Zapečené bramborové noky s dýní a cizrnou,98.0
22,2026-04-22,Hlavní jídlo,"VEGAN Smažený sýr gouda, vařené brambory, vega...",107.0
23,2026-04-22,Hlavní jídlo,"Srnčí ragú na víně, karlovarské knedlíky",129.0
24,2026-04-23,Polévka,Hrstková polévka,22.0
25,2026-04-23,Hlavní jídlo,"Plněné papriky přírodní, vařené brambory",106.0
26,2026-04-23,Hlavní jídlo,"Kuřecí maso kung - pao, jasmínová rýže",86.0
27,2026-04-23,Hlavní jídlo,"Ovocné knedlíky s tvarohem, cukrem a jogurtový...",108.0
28,2026-04-23,Hlavní jídlo,"Falafel s s míchaným salátem, 1/2 smažené hran...",124.0
29,2026-04-23,Hlavní jídlo,"Wrap s BBQ omáčkou , pečeným kuřecím stehenním...",108.0

In [7]:
df.to_csv("menza_prices.csv",index=False)